/*
 * Copyright © 2018 www.muvi.com
 *
 * @author  Sunil Kumar Behera <sunilkumar@muvi.com>
 */

package com.seleniumtests.webpage;

import static com.seleniumtests.core.CustomAssertion.assertEquals;

import static com.seleniumtests.core.Locator.locateByXPath;
import static org.testng.Assert.assertTrue;

import java.util.HashMap;
import java.util.Map;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import com.seleniumtests.core.SeleniumTestsContextManager;
import com.seleniumtests.core.TestLogging;
import com.seleniumtests.dataobject.WebUIData;
import com.seleniumtests.webelements.ButtonElement;
import com.seleniumtests.webelements.CheckBoxElement;
import com.seleniumtests.webelements.HtmlElement;
import com.seleniumtests.webelements.PageObject;
import com.seleniumtests.webelements.SelectList;
import com.seleniumtests.webelements.TextFieldElement;

public class WatchHistory extends PageObject {
	public static String url = null;
	public static String URL = null;

	public static Map<Object, Map<Object, Object>> mastermap = new HashMap<Object, Map<Object, Object>>();

	public WatchHistory(final boolean openPageURL) throws Exception {

		super(HtmlPage, openPageURL ? url = SeleniumTestsContextManager.getThreadContext().getAppURL() : null);
	}

	private static final ButtonElement HtmlPage = new ButtonElement("Click on Login button ", locateByXPath("//html"));
	private static final ButtonElement checkCheckBoxIsCkickorNot = new ButtonElement("check Check Box Is Click or Not",
			locateByXPath("//input[@id='watch']"));

	private static final ButtonElement clickOnSaveButton = new ButtonElement("Click On Save button",
			locateByXPath("//input[@id='favbtn']"));
	private static final TextFieldElement enterNumberOfDaysInTextField = new TextFieldElement("Enter number of days in textbox ",
			locateByXPath("//input[@id='duration_num']"));
	private static final HtmlElement assertMatchForSuccess = new HtmlElement("success message matching through assert",
			locateByXPath("//div[@class='alert alert-success alert-dismissable flash-msg m-t-20']"));
	private static final HtmlElement profileList = new HtmlElement("mouse over to profile list",
			locateByXPath("//a[@class='profile dropdown-toggle _user-menu']"));
	private static final HtmlElement profileWatchHistory = new HtmlElement("Match profile watch history",
			locateByXPath("//a[@class='watchhistory']"));
	private static final ButtonElement clickOnyouTubetetailsPage = new ButtonElement("Click On video details page",
			locateByXPath("//span[contains(text(),'Test AutoGenerated flow')]/../..//a[contains(text(),'YouTube Nature')]"));
	private static final ButtonElement clickOnPlayNowButton = new ButtonElement("Click On Palay now button",
			locateByXPath("//a[@class='playbtn btn btn-primary btn-lg'][contains(text(),'Play Now')]"));
	
	
	
	


	public WatchHistory SelectByText(final String Text, String xpath) throws Exception {
		waitForSeconds(1);
		SelectList s = new SelectList(Text, By.xpath(xpath));
		s.selectByText(Text);
		return this;

	}

	public WatchHistory SimulateClick(ButtonElement element) throws Exception {
		waitForSeconds(2);
		element.simulateClick();
		return this;
	}

	public WatchHistory AssertEquals(final String actualText, final String expectedText) throws Exception {
		assertEquals(actualText.toLowerCase(), expectedText.toLowerCase(), "Actual text and Expected Text Not Equal");
		return this;
	}

	public WatchHistory Click(ButtonElement element) throws Exception {

		element.waitForPresent(10);
		element.click();
		return this;
	}

	public WatchHistory Wait(int value) throws Exception {
		waitForSeconds(value);

		return this;

	}

	public WatchHistory WaitForElementPresent(final HtmlElement element) {
		element.waitForPresent(20);

		return this;
	}

	public WatchHistory MouseOver(HtmlElement element) throws Exception {

		element.waitForPresent(10);
		element.mouseOver();
		return this;
	}

	public WatchHistory SimulateMouseOver(HtmlElement element) throws Exception {

		element.waitForPresent(10);
		element.simulateMouseOver();
		return this;
	}

	public WatchHistory Textbox(TextFieldElement element, final String Text) throws Exception {

		element.clearAndType(Text);
		return this;
	}


	public WatchHistory AssertTrue(final Boolean actualText2) throws Exception {
		assertTrue(actualText2, "Text should  be visible but now its not visible");
		return this;
	}

	public WatchHistory Clickat(ButtonElement element) throws Exception {

		element.waitForPresent(10);
		element.clickAt();
		return this;
	}




	public WatchHistory pressEnter() throws Exception {
		Actions act = new Actions(driver);
		act.sendKeys(Keys.ENTER).perform();
		return this;
	}






	public WatchHistory pressSpace() throws Exception {
		Actions act = new Actions(driver);
		act.sendKeys(Keys.SPACE).perform();
		return this;
	}

	public WatchHistory refreshPage() throws Exception {
		refresh();
		return this;
	}

	public WatchHistory closeCurrentWindow() throws Exception {
		driver.close();
		return this;
	}

	public WatchHistory WindowSwitch(int val) throws Exception {
		TestLogging.logWebStep("select new window", false);
		driver.switchTo().window((String) driver.getWindowHandles().toArray()[val]);
		waitForSeconds(1);

		return this;
	}

	


	public WatchHistory goBackPage() {
		goBack();
		return this;
	}
	public WatchHistory Checkbox() throws Exception {
		
		final ButtonElement webelement = new ButtonElement("click on check box",
				locateByXPath("//input[@id='watch']"));

		webelement.clickAt();;
		return this;

	}

	/*public WatchHistory scrollToElement() throws Exception {

		WebElement element = driver
				.findElement(By.xpath("//span[contains(text(),'Test AutoGenerated flow')]/../..//a[contains(text(),'YouTube Nature')]"));
		Actions actions = new Actions(driver);
		actions.moveToElement(element);
		actions.click().perform();

		return this;
	}*/	
	private static final ButtonElement EmbdedFrontENDPlayButton = new ButtonElement("Clicking Front end Embded play button",
			locateByXPath("//button[@aria-label='Play']"));
	
	public WatchHistory ThirdPartyContent_play() throws Exception 
	 {
		 try {
			selectFrame(0);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		 try {
			Click(EmbdedFrontENDPlayButton).Wait(5);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		 return this;
	 }
	
	public WatchHistory pageScrollDown() throws Exception {
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,1000)");

		return this;
	}

public WebUIPage watchHistoryPageFunctionality(WebUIData WebUIData) throws Exception {
		
	new CmsDashBoard(false)
	.clickOnPreview();
	new WebUILoginPage(false)
	.ClickOnLogInForEndUser(WebUIData);
	
	
	
	     Wait(5)
	     //.scrollToElement()
	     .pageScrollDown()
		.Click(clickOnyouTubetetailsPage)
		.Click(clickOnPlayNowButton)
		
		
		
		;
		
		
		return new WebUIPage(false);
	}
	
	
	
                        
	
	public WebUIPage checkVerifyWatchHistoryIsClickOrNot(WebUIData WebUIData) throws Exception {
		
		if(checkCheckBoxIsCkickorNot.isEnabled())
		{
			Textbox(enterNumberOfDaysInTextField, WebUIData.getDuration())
			.Click(clickOnSaveButton)
			.AssertEquals(assertMatchForSuccess.getText().replace("×", "").trim(), "status updated successfully.")
			
			
			;
			new CmsDashBoard(false)
			.clickOnPreview();
			new WebUILoginPage(false)
			.ClickOnLogInForEndUser(WebUIData);
			
			MouseOver(profileList)
			.AssertEquals(profileWatchHistory.getText(), "Watch History")
			
			;
			
			
		}
		else
		{
			Checkbox()
			.Textbox(enterNumberOfDaysInTextField, WebUIData.getDuration())
			.Click(clickOnSaveButton)
			.AssertEquals(assertMatchForSuccess.getText(), "Status updated successfully.")
			
			;
		}
		
		
		
		
		
		
		return new WebUIPage(false);
	}
	
	
	

}